### ISSUE TITLE
Question about unit tests

### ISSUE THREAD

**Issue by hsolbrig** [smart-on-fhir/fhir-parser#33]
How do I verify that changes I have made to the parser haven't broken anything?   At the moment, I get the following "out of the box".

Steps:
1) copy settings.py and mappings.py from Defaults to Sample directory
2) `pip install -r requirements.txt`
3) `cd sample`
4) ../generate.py

```
...
  DEBUG    | Created class "VerificationResultValidator", module verificationresult
  INFO     | Parsing profile "VisionPrescription"
  DEBUG    | Created class "VisionPrescription", module visionprescription
  DEBUG    | Created class "VisionPrescriptionLensSpecification", module visionprescription
  DEBUG    | Created class "VisionPrescriptionLensSpecificationPrism", module visionprescription
  INFO     | Parsing profile "MetadataResource"
  DEBUG    | Created class "MetadataResource", module metadataresource
Traceback (most recent call last):
  File "../generate.py", line 33, in <module>
    spec.write()
  File "/Users/solbrig/git/smart-on-fhir/fhir-parser/fhirspec.py", line 246, in write
    renderer.render()
  File "/Users/solbrig/git/smart-on-fhir/fhir-parser/fhirrenderer.py", line 91, in render
    imports = profile.needed_external_classes()
  File "/Users/solbrig/git/smart-on-fhir/fhir-parser/fhirspec.py", line 527, in needed_external_classes
    raise Exception('There is no class "{}" for property "{}" on "{}" in {}'.format(prop_cls_name, prop.name, klass.name, self.name))
Exception: There is no class "Http://hl7.org/fhirpath/System.String" for property "id" on "Element" in Element
```

**Comment by hsolbrig** [comment]
Cockpit error.  Didn't use the "-f" option in generate so locked into R5 issues.
