### ISSUE TITLE
generate.py fails to download FHIR specs file

### ISSUE THREAD

**Issue by goffioul** [smart-on-fhir/fhir-parser#37]
Using `master` branch (4607aad9fc8de63eb6119a8498029c658b07b224), I copied the default `settings.py` and `mappings.py` at top-level then ran `./generate.py`:
```
INFO:root:Install "colorlog" to enable colored log messages
INFO:fhirparser:Downloading version.info
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): hl7.org:80
DEBUG:urllib3.connectionpool:http://hl7.org:80 "GET /fhir/2018May//version.info HTTP/1.1" 404 6977
Traceback (most recent call last):
  File "./generate.py", line 25, in <module>
    spec_source = loader.load(force_download=force_download, force_cache=force_cache)
  File "/path/to/fhir-parser/fhirloader.py", line 48, in load
    filename = self.download(remote)
  File "/path/to/fhir-parser/fhirloader.py", line 75, in download
    raise Exception("Failed to download {}".format(url))
Exception: Failed to download http://hl7.org/fhir/2018May//version.info
```

**Comment by mikix** [comment]
This should be fixed now - the default config points at R4 not 2018May
